name: Hibernate Reactive CI

on:
  push:
    branches:
      - testing-release

# See https://github.com/hibernate/hibernate-orm/pull/4615 for a description of the behavior we're getting.
concurrency:
  # Consider that two builds are in the same concurrency group (cannot run concurrently)
  # if they use the same workflow and are about the same branch ("ref") or pull request.
  group: "workflow = ${{ github.workflow }}, ref = ${{ github.event.ref }}, pr = ${{ github.event.pull_request.id }}"
  # Cancel previous builds in the same concurrency group even if they are in process
  # for pull requests or pushes to forks (not the upstream repository).
  cancel-in-progress: ${{ github.event_name == 'pull_request' || github.repository != 'hibernate/hibernate-reactive' }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2.2.0
      with:
        distribution: 'temurin'
        java-version: 11
    - name: Create artifacts
      run: ./gradlew assemble
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.HIBERNATE_ORG_SSH_KEY }}
        name: id_rsa_hibernate.org
        known_hosts: ${{ secrets.HIBERNATE_ORG_SSH_KNOWN_HOSTS }}
        config: |
          Host github.com
            User hibernate
            IdentityFile ~/.ssh/id_rsa_hibernate.org
    - name: Setup git user name and email
      run: |
        git config user.name "GitHub Actions"
        git config user.email "<>"
    - name: Publish documentation on Hibernate.org
      run: ./gradlew publishDocumentation -PdocPublishBranch=staging