# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  mysql:
    runs-on: ubuntu-latest
    container: 
     image: mysql
     env:
       MYSQL_ROOT_PASSWORD: hibernate-rx
       MYSQL_DATABASE: hibernate-rx
       MYSQL_USER: hibernate-rx  
       MYSQL_PASSWORD: hibernate-rx  
     ports:
       - 3306
  postgres:
    runs-on: ubuntu-latest
    container: 
     image: postgres
     env:
       POSTGRES_DB: hibernate-rx
       POSTGRES_USER: hibernate-rx
       POSTGRES_PASSWORD: hibernate-rx  
     ports:
       - 5432
  build:
    runs-on: ubuntu-latest
    needs: [mysql, postgres]
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
