name: Latest Vert.x 4.x

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    # * is a special character in YAML, so you have to quote this string
    # Run every hour at minute 25
    - cron: '25 * * * *'

# See https://github.com/hibernate/hibernate-orm/pull/4615 for a description of the behavior we're getting.
concurrency:
  # Consider that two builds are in the same concurrency group (cannot run concurrently)
  # if they use the same workflow and are about the same branch ("ref") or pull request.
  group: "workflow = ${{ github.workflow }}, ref = ${{ github.event.ref }}, pr = ${{ github.event.pull_request.id }}"
  # Cancel previous builds in the same concurrency group even if they are in process
  # for pull requests or pushes to forks (not the upstream repository).
  cancel-in-progress: ${{ github.event_name == 'pull_request' || github.repository != 'hibernate/hibernate-reactive' }}

jobs:
  # The examples test the Hibernate ORM Gradle plugin. We use it for bytecode enhancements.
  test_dbs:
    name: Test with ${{ matrix.db }} and latest Vert.x in ${{ matrix.vertx-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        vertx-version: [ '[4.2,4.3)' ]
        db: [ 'Oracle' ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Print the effective Vert.x version used
        run: ./gradlew :hibernate-reactive-core:dependencyInsight --dependency io.vertx -PvertxVersion='${{ matrix.vertx-version }}' -PenableSonatypeOpenSourceSnapshotsRep
      - name: Build and Test with ${{ matrix.db }}
        run: ./gradlew build -Pdb=${{ matrix.db }} -Pdocker -PvertxVersion='${{ matrix.vertx-version }}' -PenableSonatypeOpenSourceSnapshotsRep -PshowStandardOutput -PincludeTests=LazyManyToOneAssociationTest
